chore: add nginx config for llm-search, set rate-limiting
Informasjonsforvaltning/fdk-infra pull request #199
Opened 2024-08-08 12:34 UTC by valosnah

2024-08-08 12:48 UTC, jeffreiffers requested changes

2024-08-08 12:48 UTC, jeffreiffers commented on apps/base/nginx-llm-search/config-map.yaml
> +      open_file_cache max=1000 inactive=20s;
Usikker om vi trenger caching og hva er bivirkningene

2024-08-08 12:48 UTC, jeffreiffers commented on apps/base/nginx-llm-search/config-map.yaml
> +      client_max_body_size  20M;
den kan settes ned til 1M? Vi har verken jwt eller stor body

2024-08-08 12:48 UTC, jeffreiffers commented on apps/base/nginx-llm-search/config-map.yaml
> +
Stenge helse endepunkter og metrics? Se I llm deployment.

2024-08-08 12:58 UTC, valosnah commented on apps/base/nginx-llm-search/config-map.yaml
> +      open_file_cache max=1000 inactive=20s;
Enig, fjerner

2024-08-08 12:59 UTC, valosnah commented on apps/base/nginx-llm-search/config-map.yaml
> +      client_max_body_size  20M;
Done

2024-08-08 13:00 UTC, valosnah commented on apps/base/nginx-llm-search/config-map.yaml
> +
Ah de glemte jeg helt, legger til

2024-08-09 11:48 UTC, jeffreiffers approved these changes

2024-08-14 13:34 UTC, closed without merging